services:
  paper:
    image: eclipse-temurin:21-jdk
    container_name: siose-mc-dev
    working_dir: /server
    command: ["java", "-Xms2G", "-Xmx2G", "-jar", "paper.jar", "--nogui"]
    ports:
      - "25565:25565"

    environment:
      - SIOSE_API_BASE_URL=https://your-api-endpoint.com

    volumes:
      - ./paper.jar:/server/paper.jar
      - ./eula.txt:/server/eula.txt
      - ./server.properties:/server/server.properties
      - ./plugins:/server/plugins
      - ./world:/server/world

    stdin_open: true
    tty: true
